name: build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Download sources
        uses: actions/checkout@v1

      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests
      #   run: |
      #     npm run test:eslint
      #     npm run test:mocha

      # - name: Generate files
      #   run: npm run build

      - name: Generate files
        run: |
          mkdir bin
          echo "example" > bin/static.js
          mkdir -p lib/node_modules/functions
          echo "example" > lib/exports.js
          echo "example" > lib/node_modules/functions/myfunction.js

      - name: Run a script
        run: bash -e ./src/release.sh

      - name: On Failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" --data "{ \"content\": \"❌ Failed to BUILD, [see logs](https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks)\" }" $DISCORD_WEBHOOK

