name: Notifications
on:
  push:
    branches:
      - '**'

jobs:
  notify:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      ACTION_ERROR: "false"
    steps:
      - name: Initialize
        run: |
          echo OK

      - name: Build
        run: |
          echo FAIL
          exit 1

      - if: failure()
        run: echo ::set-env name=ACTION_ERROR::true

      - if: success() || failure()
        run: |
          echo "ACTION_ERROR is $ACTION_ERROR"

